### PR TITLE
Fix something and more

### PR DESCRIPTION
**Pull request by ElectroBoy404NotFound**
Check commites

### CODE REVIEW

**Comment by ElectroBoy404NotFound** [comment]
Nice OS also!

**Comment by darshdudhia** [comment]
Thanks Have you Tested it works?

**Comment by darshdudhia** [comment]
also remember you have to change this file for a new command to work :https://github.com/darshdudhia/DarshOS/blob/main/os/Kernel_Utils/Keyboard%26%26Shell.cpp

**Comment by ElectroBoy404NotFound** [comment]
ok, also i did test it, and the command thing i left it alone

**Comment by darshdudhia** [comment]
ok

**Pull request merged**
